# Generated by Django 2.2.4 on 2023-11-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0002_auto_20231126_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
