# Generated by Django 2.2.4 on 2023-11-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojo_ninja_shell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
