# Generated by Django 2.2.4 on 2023-11-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojo_ninja_shell', '0003_dojo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='desc',
        ),
    ]
