# Generated by Django 2.2.4 on 2023-11-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojo_ninja_shell', '0005_dojo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='old dojo'),
        ),
    ]
