# Generated by Django 2.2.4 on 2023-11-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojo_ninja_shell', '0006_auto_20231119_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='desc',
        ),
    ]
