# Generated by Django 2.2.4 on 2023-11-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books_authors_shell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
