# Generated by Django 2.2.4 on 2023-11-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tv_shows', '0003_auto_20231127_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
